Fixed multichannel vtk2sitk and added test
SimpleITK/SimpleITKUtilities pull request #36
Opened 2023-08-23 18:46 UTC by dave3d

2023-08-23 18:53 UTC, zivy requested changes

2023-08-23 18:53 UTC, zivy commented on test/test_vtk.py
> +    print(vtk_img)
Please remove the print, doesn't help with understanding what went wrong when something isn't as expected.

2023-08-23 18:59 UTC, blowekamp commented
Thank you for working on this. What about sitk2vtk for multichannel images?

2023-08-23 19:07 UTC, dave3d commented
> Thank you for working on this. What about sitk2vtk for multichannel images?

That works also. I guess I should explicitly test that too.

2023-08-23 19:13 UTC, blowekamp commented
And please check if the documentation needs these details too.

2023-08-28 15:59 UTC, zivy approved these changes

2023-08-28 16:18 UTC, merged